### PR TITLE
Fix authentication workflow

### PR DESCRIPTION
**Pull request by Galunid**
Fix issue discussed in https://github.com/koreader/koreader/issues/6087
It seems authentication workflow got updated(https://dev.evernote.com/doc/articles/authentication.php)
I tested it in emulator and I was able to log in.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/evernote-sdk-lua/2)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Weird that they'd change the URL without changing anything else.

**Comment by Galunid** [comment]
Indeed, I don't really see any reason, but at least we don't have to rewrite half of the code :). I'll test it on my other devices, just to triple check, but it seemed to work.

**Comment by Galunid** [comment]
Triple checked, I can login and export notes.

**Comment by Frenzie** [comment]
Could you also submit a PR for this line? https://github.com/koreader/koreader-base/blob/989d3a92b90872b67430fd7fae88ac84e52c05bc/thirdparty/evernote-sdk-lua/CMakeLists.txt#L20

**Pull request merged**
